<?php require ('header.phtml') ?>
    <div class="main d-flex flex-column h-100">
        <div>
            <h1 class="text-center">Let's Get Weird</h1>
        </div>
        <div class="d-flex flex-column justify-content-around align-items-stretch h-100">
            <div class="d-flex flex-fill flex-grow-1 align-items-stretch align-content-stretch ">
                <div class="player-container bg-light m-2 col-6 float-left">
                    <h3>Player 1</h3>
                    <div class="round-container" style="display: none"></div>
                    <div class="dice-container" ></div>
                </div>
                <div class="player-container bg-light m-2 col-6 float-right">
                    <h3>Player 2</h3>
                    <div class="round-container" style="display: none"></div>
                    <div class="dice-container" ></div>
                </div>
            </div>
            <div class="d-flex justify-content-around">
                
                <div class="col-4 d-flex justify-content-end">
                    <span class="d-flex" id="round-label"></span>
                </div>
                <div class="col-4 d-flex justify-content-center">
                    <button class="d-flex btn btn-primary" id="roll-button">Roll the dice</button>
                </div>
                <div class="col-4 d-flex justify-content-start">
                    <span id="winner-label">&nbsp;</span>
                </div>
            </div>
            <div class="d-flex flex-fill flex-grow-1 align-items-stretch align-content-stretch">
                <div class="player-container bg-light m-2 col-6 float-left">
                    <h3>Player 3</h3>
                    <div class="round-container" style="display: none"></div>
                    <div class="dice-container" ></div>
                </div>
                <div class="player-container bg-light m-2 col-6 float-right">
                    <h3>Player 4</h3>
                    <div class="round-container" style="display: none"></div>
                    <div class="dice-container" ></div>
                </div>
            </div>
        </div>
    </div> 
    <!-- Modal -->
    <div class="modal fade" id="loadModal" tabindex="-1" role="dialog" aria-labelledby="loadModalLabel">
        <div class="modal-dialog modal-sm" role="document">
            <div class="modal-content">
                <div class="modal-body text-center">
                    <div class="loader"></div>
                    <div clas="loader-txt">
                        <p>Rolling the dice. <br><br><small>Enjoy the game... #love</small></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php require ('footer.phtml') ?>
